channels:
  - conda-forge
dependencies:
  - bokeh=3.2.2
  - conda-lock=2.1.2
  - git=2.41.0
  - jupyter=1.0.0
  - mamba=1.4.9
  - matplotlib=3.7.2
  - nbgitpuller=1.2.0
  - numpy=1.25.2
  - pandas=2.0.3
  - pillow=10.0.0
  - pip=23.2.1
  - python=3.10
  - setuptools=68.1.2
  - pip:
    - nbconvert[webpdf]
